version: '3.8'

services:
  optimizer:
    image: ghcr.io/twanariens/ariensdesignoptimizer:latest
    container_name: adoptimizer
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - API_TOKEN=eK7Mtf_FU0bCi4SnUPzIZayNymnuzqtOT2oKt9LNj-Y
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./app:/app
    networks:
      - proxy
    depends_on:
      - redis

  worker:
    image: ghcr.io/twanariens/ariensdesignoptimizer:latest
    container_name: adoptimizer-worker
    restart: unless-stopped
    command: celery -A app.celery worker --loglevel=info
    environment:
      - API_TOKEN=eK7Mtf_FU0bCi4SnUPzIZayNymnuzqtOT2oKt9LNj-Y
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./app:/app
    depends_on:
      - redis
    networks:
      - proxy

  redis:
    image: redis:7
    container_name: adoptimizer-redis
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
