name: Auto-build & release Docker image to GHCR

on:
  push:
    branches: [master]

jobs:
  version-release-build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git fetch --tags

      - name: Determine next free version
        id: version
        run: |
          git fetch --tags

          major=1
          minor=0
          patch=1

          while git rev-parse "v${major}.${minor}.${patch}" >/dev/null 2>&1; do
            patch=$((patch+1))
          done

          version="v${major}.${minor}.${patch}"
          echo "Next free version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ steps.version.outputs.version }}
          labels: |
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
          tags: |
            ghcr.io/twanariens/ariensdesignoptimizer:latest
            ghcr.io/twanariens/ariensdesignoptimizer:${{ steps.version.outputs.version }}

